name: CI

on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby-version: [3.1, 3.0.6]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          submodules: recursive

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache

      - name: Run ${{ matrix.os }} tests
        shell: bash
        run: script/cibuild
